# Generated by Django 4.2.13 on 2024-05-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_formdata_remove_ingredient_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='minprem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
